import assert from 'node:assert/strict';
import {KartGame,trackAt,TRACK_LENGTH,TOTAL_DISTANCE} from './dist/kart-engine.js';
const pack=Array.from({length:16},(_,i)=>({word:'word'+i,meaning:'意味'+i}));
const fresh=()=>{const g=new KartGame(pack,{random:()=>.42});g.start();for(let i=0;i<13;i++)g.tick(.25);return g;};
function drive(g,hz=60,correct=true){let count=0;const questions=[];while(g.phase!=='done'&&count++<hz*300){if(g.phase==='quiz'){questions.push(g.pair.word);const position=g.distance,ai=g.ai.map(a=>a.distance),time=g.time;g.tick(.2);assert.equal(g.distance,position);assert.deepEqual(g.ai.map(a=>a.distance),ai);assert.equal(g.time,time);const index=g.options.findIndex(p=>correct?p.word===g.pair.word:p.word!==g.pair.word);g.answer(index);assert.equal(g.answer(index),false);g.continue();}if(g.phase==='race'){const p=trackAt(g.distance);g.input((-p.curve*g.speed*g.speed*.12-g.lateral*2)/6.5,false);if(g.item)g.useItem();}g.tick(1/hz);}assert.equal(g.phase,'done','must finish');return questions;}
assert.throws(()=>new KartGame(pack.slice(0,3)));assert.ok(TRACK_LENGTH>700&&TRACK_LENGTH<1500);assert.ok(Math.abs(trackAt(0).x-trackAt(TRACK_LENGTH).x)<1e-8);
let g=fresh();assert.equal(g.phase,'race');g.input(1,true);g.pause(true);const old=g.distance;g.tick(.2);assert.equal(g.distance,old);assert.equal(g.steer,0);assert.equal(g.useItem(),false);g.pause(false);assert.equal(g.drifting,false);
g=fresh();g.drifting=true;g.drift=1;g.input(0,false);assert.equal(g.boost,1);assert.equal(g.driftCount,1);g.input(0,false);assert.equal(g.driftCount,1);g.drifting=true;g.drift=2;g.input(0,false);assert.equal(g.boost,1.8);
g=fresh();g.item='turbo';assert.equal(g.useItem(),true);assert.equal(g.item,null);assert.equal(g.useItem(),false);g.item='pulse';g.ai.forEach(a=>a.distance=g.distance+100);assert.equal(g.useItem(),false);assert.equal(g.item,'pulse');g.ai[0].distance=g.distance+20;assert.equal(g.useItem(),true);assert.ok(g.ai[0].slow>0);g.item='shield';g.useItem();g.hit();assert.equal(g.slow,0);g.shield=0;g.hit();assert.ok(g.slow>0);
const wins=[];for(const hz of[30,60,120]){g=fresh();const qs=drive(g,hz);assert.equal(g.correct,9);assert.equal(g.answered,9);assert.equal(qs.length,9);assert.equal(g.distance,TOTAL_DISTANCE);assert.equal(g.starTotal,g.events.filter(e=>e.type==='reward').reduce((s,e)=>s+e.points,0));assert.equal(new Set(g.events.filter(e=>e.type==='reward').map(e=>e.key)).size,g.events.filter(e=>e.type==='reward').length);const time=g.time,stars=g.starTotal;g.tick(.2);assert.equal(g.time,time);assert.equal(g.starTotal,stars);wins.push({hz,rank:g.finishedRank,time:g.time});}
const wrong=fresh();drive(wrong,60,false);assert.equal(wrong.correct,0);assert.equal(wrong.itemsUsed,0);assert.ok(wrong.time>wins[1].time+5,'correct words materially accelerate race');assert.ok(wins[1].rank<wrong.finishedRank,'correct words improve rank under same driving');assert.equal(wrong.startReview(),true);let guard=0;while(wrong.phase!=='reviewDone'&&guard++<30){assert.equal(wrong.reverse,true);wrong.answer(wrong.options.findIndex(p=>p.word===wrong.pair.word));wrong.continue();}assert.equal(wrong.phase,'reviewDone');
// Small vocabulary deck and delayed retry: never undefined, valid choices, repeats after at least two questions.
for(const rng of[()=>0,()=>.42,()=>.999]){g=new KartGame(pack.slice(0,4),{random:rng});const seen=[];for(let i=0;i<9;i++){g.ask();assert.ok(g.pair);assert.equal(g.options.length,4);const word=g.pair.word;assert.ok(!seen.slice(-2).includes(word),'retry spaced by 2 questions');seen.push(word);g.answer(g.options.findIndex(p=>p.word!==word));g.continue();}}
console.log('PASS 3-lap/9-gate race at 30/60/120Hz; all-car quiz pause; input clearing; drift tiers; item guards; ranking; word boost impact; delayed retries; reverse review; terminal/reward protection.');console.log(JSON.stringify({correct:wins,wrong:{rank:wrong.finishedRank,time:wrong.time}},null,2));
