import assert from 'node:assert/strict';
import {FishingGame,FISH,RODS} from './dist/fishing-engine.js';
const pack=Array.from({length:20},(_,i)=>({word:'word'+i,meaning:'意味'+i}));
const answer=g=>g.answer(g.options.indexOf(g.pair));
const cast=g=>{for(let i=0;i<35;i++)g.tick(1/60);assert.equal(g.cast(),true);assert.equal(g.perfect,true);};
function hook(f=FISH[0],rod=0){const g=new FishingGame(pack,()=>.42);g.next();g.targets=[f];g.setRod(rod);g.select(f.id);answer(g);cast(g);return g;}
function play(g,hz=60){for(let i=0;i<hz*35&&['reel','quiz'].includes(g.phase);i++){if(g.phase==='quiz'){answer(g);continue;}g.hold(['calm','stunned'].includes(g.behavior)&&g.tension<62);if(g.energy&&g.cooldown===0&&g.progress<85&&(g.behavior==='rush'||g.elapsed>10))g.special();g.tick(1/hz);}return g.phase;}
assert.throws(()=>new FishingGame(pack.slice(0,3)));
let g=new FishingGame(pack,()=>.42);g.next();assert.equal(g.setRod(90),false);assert.equal(g.select(99),false);g.select(g.targets[0].id);assert.equal(new Set(g.options.map(p=>p.meaning)).size,4);g.answer(g.options.findIndex(p=>p!==g.pair));assert.equal(g.phase,'escaped');assert.equal(g.energy,0);assert.equal(g.score,0);assert.equal(g.special(),false);assert.equal(g.cast(),false);
g=hook();g.hold(true);for(let i=0;i<600;i++)g.tick(1/60);assert.equal(g.phase,'escaped');assert.match(g.reason,/糸/);
g=hook();for(let i=0;i<1700;i++)g.tick(1/60);assert.equal(g.phase,'escaped');assert.match(g.reason,/逃げ/);
g=hook();g.hold(true);g.pause(true);const time=g.elapsed;g.tick(.2);assert.equal(g.elapsed,time);assert.equal(g.special(),false);assert.equal(g.held,false);g.pause(false);assert.equal(g.held,false);
g=hook();const energy=g.energy;assert.equal(g.special(),true);assert.equal(g.energy,energy-1);assert.equal(g.special(),false);assert.ok(g.stun>0);assert.ok(g.tension<22);
const scores=[];for(const hz of [30,60,120])for(const f of FISH)for(let rod=0;rod<RODS.length;rod++){g=hook(f,rod);assert.equal(play(g,hz),'caught',`${f.name} ${RODS[rod].name} ${hz}Hz`);assert.equal(g.catches.length,1);assert.equal(g.special(),false);const score=g.score;g.tick(.1);assert.equal(g.score,score);scores.push(score);}
g=hook(FISH[5]);while(g.phase==='reel'){g.hold(g.behavior==='calm'&&g.tension<60);g.tick(1/60);}assert.equal(g.phase,'quiz');assert.equal(g.quizKind,'boost');const before=g.progress;g.answer(g.options.findIndex(p=>p!==g.pair));assert.equal(g.phase,'correction');assert.equal(g.progress,before-15);assert.equal(g.held,false);const elapsed=g.elapsed;g.tick(.2);assert.equal(g.elapsed,elapsed);assert.equal(g.acknowledge(),true);assert.equal(g.phase,'reel');assert.equal(g.acknowledge(),false);assert.equal(play(g),'caught');
// Full 8-cast journey, no state fixtures: fever, mission rewards and final boss.
g=new FishingGame(pack,()=>.42);let fever=0;for(let i=0;i<8;i++){assert.equal(g.next(),true);if(g.fever)fever++;assert.equal(g.next(),false);g.setRod(0);g.select(g.targets.reduce((a,b)=>a.hard<b.hard?a:b).id);answer(g);cast(g);assert.equal(play(g),'caught');}assert.equal(g.round,8);assert.equal(g.catches.at(-1).id,5);assert.equal(g.missions.size,3);assert.ok(fever>=2);assert.equal(g.score,g.events.filter(e=>e.type==='reward').reduce((n,e)=>n+e.points,0));assert.equal(new Set(g.events.filter(e=>e.type==='reward').map(e=>e.key)).size,g.events.filter(e=>e.type==='reward').length);assert.equal(g.next(),true);assert.equal(g.phase,'done');assert.equal(g.next(),false);assert.equal(g.catches.length,8);console.log('PASS: 54 fish/rod/frame-rate battles, full 8-cast journey, word gating, tension/timeout failures, special cost/cooldown, pause, boss vocabulary counterattack, fever, mission reward accounting, terminal guards.');
